# Generated by Django 5.0.1 on 2024-01-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qrcafe.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
