# Generated by Django 5.0.1 on 2024-01-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0006_product_category_product_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/image/product_image'),
        ),
    ]
