# Generated by Django 5.0.1 on 2024-01-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0008_product_last_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_price',
            new_name='previous_price',
        ),
    ]
