# Generated by Django 5.0.1 on 2024-01-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opening_hours',
            field=models.CharField(blank=True, default='Pazartesi - Pazar (09:00 24:00)', max_length=255, null=True),
        ),
    ]
