# Generated by Django 5.0.1 on 2024-01-22 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
