# Generated by Django 5.0.1 on 2024-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0013_message_date_joined_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
