# Generated by Django 5.0.1 on 2024-01-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0014_alter_product_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='qrcafe.category'),
            preserve_default=False,
        ),
    ]
