# Generated by Django 5.0.1 on 2024-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0016_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
