# Generated by Django 5.0.1 on 2024-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0017_company_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
