# Generated by Django 5.0.1 on 2024-01-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0018_category_description_en_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mission_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vision_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
