# Generated by Django 5.0.1 on 2024-02-03 07:05

import qrcafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0019_company_about_us_en_company_mission_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/image/category_image', validators=[qrcafe.models.validate_image_dimensions]),
        ),
    ]
