# Generated by Django 5.0.1 on 2024-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0020_product_rating_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
