# Generated by Django 5.0.1 on 2024-02-03 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0023_category_created_by_category_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
