# Generated by Django 5.0.1 on 2024-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0025_alter_category_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.TimeField(),
        ),
    ]
