# Generated by Django 5.0.1 on 2024-02-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0028_product_selected_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selected_product',
            new_name='showcase_product',
        ),
    ]
