# Generated by Django 5.0.1 on 2024-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0029_rename_selected_product_product_showcase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
