# Generated by Django 5.0.1 on 2024-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0030_alter_product_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
