# Generated by Django 5.0.2 on 2024-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0033_rezervation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervation',
            name='hours',
            field=models.CharField(max_length=255),
        ),
    ]
