# Generated by Django 5.0.2 on 2024-02-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0034_alter_rezervation_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rezervation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
