# Generated by Django 5.0.2 on 2024-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0035_delete_rezervation_delete_table_gallery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
