# Generated by Django 5.0.2 on 2024-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0036_message_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='index_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='index_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
