# Generated by Django 5.0.2 on 2024-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcafe', '0037_company_index_text_company_index_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='iframe',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
